package com.sbm.mc.sevenroomstoreviewpro.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ResCustomFieldAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResCustomFieldAllPropertiesEquals(ResCustomField expected, ResCustomField actual) {
        assertResCustomFieldAutoGeneratedPropertiesEquals(expected, actual);
        assertResCustomFieldAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResCustomFieldAllUpdatablePropertiesEquals(ResCustomField expected, ResCustomField actual) {
        assertResCustomFieldUpdatableFieldsEquals(expected, actual);
        assertResCustomFieldUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResCustomFieldAutoGeneratedPropertiesEquals(ResCustomField expected, ResCustomField actual) {
        assertThat(expected)
            .as("Verify ResCustomField auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResCustomFieldUpdatableFieldsEquals(ResCustomField expected, ResCustomField actual) {
        assertThat(expected)
            .as("Verify ResCustomField relevant properties")
            .satisfies(e -> assertThat(e.getSystemName()).as("check systemName").isEqualTo(actual.getSystemName()))
            .satisfies(e -> assertThat(e.getDisplayOrder()).as("check displayOrder").isEqualTo(actual.getDisplayOrder()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getValue()).as("check value").isEqualTo(actual.getValue()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResCustomFieldUpdatableRelationshipsEquals(ResCustomField expected, ResCustomField actual) {
        assertThat(expected)
            .as("Verify ResCustomField relationships")
            .satisfies(e -> assertThat(e.getReservation()).as("check reservation").isEqualTo(actual.getReservation()));
    }
}
